name: Majsoul-Login
on:
  workflow_dispatch:
  schedule: #10:00
   - cron: '0 2 * * *'
jobs:
  login:
    name: Majsoul-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Selenium
        run: pip install selenium==4.17.2

      - name: Majsoul login
        run: python login.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}
